version: "3" # 버전 지정

services: # 컨테이너 설정
  db:   
    images: mysql:8.1 # 컨테이너에서 사용하는 base image 지정
    restart: always # 컨테이너 다운 시 재시작하라는 명령어
    volumes: # -v 옵션과 동일
      - ./mysqldata:/var/lib/mysql
    environment: # 컨테이너 안의 환경변수 설정
      - MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports: # -p 옵션과 동일
      - "3306:3306"
  redis:
    # 사용할 이미지
    image: redis:latest
    # 접근 포트 설정(컨테이너 외부(바인딩할 포트):컨테이너 내부)
    ports:
      - ${REDIS_BINDING_PORT}:${REDIS_PORT}
    # 스토리지 마운트(볼륨) 설정
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_DEFAULT_FILE}:/usr/local/conf/redis.conf
    # 컨테이너에 docker label을 이용해서 메타데이터 추가
    labels:
      - "name=redis"
      - "mode=standalone"
    # 컨테이너 종료시 재시작 여부 설정
    restart: always
    command: redis-server /usr/local/conf/redis.conf