name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
      id-token: write
      contents: read

jobs:
  Build-and-Push-Docker-Image: 
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Nodejs 18
        uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          cache: 'npm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: dmg-api
          IMAGE_TAG: latest
        run: |
          sudo docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG

      # - name: executing remote ssh commands using ssh key
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_PEM_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     run: |
      #       ssh -i ${SSH_PEM_KEY} -p ${SSH_PORT} ${SSH_USER}@${SSH_HOST}


# sudo docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .